[HAB-138] Images
owengretzinger/habits-together pull request #117
Opened 2024-09-05 02:01 UTC by AnkushSarkar10

2024-09-06 15:32 UTC, AnkushSarkar10 commented
dont merge

2024-09-06 18:10 UTC, owengretzinger requested changes
editprofile page pfp is not working for me

<img width="509" alt="image" src="https://github.com/user-attachments/assets/08fbe1e9-38a1-4fbd-a22f-903dae4c59de">

2024-09-06 18:10 UTC, owengretzinger commented on mobile-app/src/app/(app)/friends/editprofile.tsx
> +        f
remove this "f"

2024-09-06 18:10 UTC, owengretzinger commented on mobile-app/src/atoms/atoms.ts
> +  ({ userId }: { userId: UserIdT }) =>
Why does this take an object as an argument? You could do it without

2024-09-07 02:23 UTC, owengretzinger approved these changes

2024-09-07 02:23 UTC, merged