Added HabitView Modal
owengretzinger/habits-together pull request #82
Opened 2024-06-28 21:23 UTC by himikheal

Made clicking a habit from friend view open a modal instead of a screen. Did not fix the modal being underneath.

2024-07-03 01:24 UTC, AnkushSarkar10 requested changes

2024-07-03 21:51 UTC, owengretzinger requested changes

2024-07-03 21:51 UTC, owengretzinger commented on mobile-app/src/components/habit-components/HabitCard.tsx
> +}) {
This seems confusing to me. How about instead, you have an openAsModal argument that defaults to false?

2024-07-03 21:51 UTC, owengretzinger commented on mobile-app/src/components/habit-components/HabitCard.tsx
> +        pathname: screenType.concat("/viewhabit"),
And then here just do a check

pathname: openAsModal? "modals/viewhabit" : "viewhabit"

2024-07-04 01:08 UTC, owengretzinger approved these changes

2024-07-04 01:24 UTC, AnkushSarkar10 approved these changes

2024-07-04 01:24 UTC, merged